env:
  PYTHON_VERSION: 3.10
  GITHUB_TOKEN: ENCRYPTED[13da504dc34d1608564d891fb7f456b546019d07d1abb059f9ab4296c56ccc0e6e32c7b313629776eda40ab74a54e95c]
  # The above token, is a GitHub API Token, that allows us to download RipGrep without concern of API limits

arm_linux_task:
  alias: linux
  arm_container:
    image: node:18
    memory: 8G
  env:
    USE_SYSTEM_FPM: 'true'
  prepare_script:
    - mkdir test_fetching_ripgrep
    - cd test_fetching_ripgrep
    - npm init -y --verbose
    - npm install --verbose --foreground-scripts @vscode/ripgrep; cat /root/.npm/_logs/*.log
    - rm -rfv /tmp/vscode-ripgrep-cache*/
    - npm ci --verbose --foreground-scripts; cat /root/.npm/_logs/*.log
    - rm -rfv /tmp/vscode-ripgrep-cache*/
    - npm ci --verbose --foreground-scripts; cat /root/.npm/_logs/*.log
    - rm -rfv /tmp/vscode-ripgrep-cache*/
    - npm ci --verbose --foreground-scripts; cat /root/.npm/_logs/*.log
    - rm -rfv /tmp/vscode-ripgrep-cache*/
    - npm ci --verbose --foreground-scripts; cat /root/.npm/_logs/*.log
    - rm -rfv /tmp/vscode-ripgrep-cache*/
    - npm ci --verbose --foreground-scripts; cat /root/.npm/_logs/*.log
