linux_task:
  skip: $CIRRUS_CHANGE_IN_REPO == $CIRRUS_LAST_GREEN_CHANGE
  env:
    CIRRUS_CLONE_DEPTH: 1
  container:
    image: node:16-slim
    cpu: 1
    timeout_in: 6s
  echo_env_vars_script:
    - echo "CIRRUS_CRON is: xyz--${CIRRUS_CRON}--xyz"
    - echo "CIRRUS_TAG is: xyz--${CIRRUS_TAG}--xyz"
    - echo "CIRRUS_CHANGE_IN_REPO is: xyz--${CIRRUS_CHANGE_IN_REPO}--xyz"
    - echo "CIRRUS_LAST_GREEN_CHANGE is: xyz--${CIRRUS_LAST_GREEN_CHANGE}--xyz"

silently_mark_unscheduled_builds_as_failed_task:
  skip_notifications: true
  only_if: $CIRRUS_CRON == "" && $CIRRUS_TAG == ""
  timeout_in: 12s
  clone_script: |
    true # This command does nothing other than exit with status 0 (a "clean" status code)
  env:
    CIRRUS_CLONE_DEPTH: 1
  container:
    image: alpine:latest
    cpu: 1
  mark_task_as_failed_script:
    - false # This command does nothing other than exit with status 1 (an "error" status code)
