name: Package tests for Pulsar
on:
  - push
  - pull_request
jobs:
  setup:
    name: setup
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install windows-build-tools
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        npm i --global windows-build-tools@4.0.0
        npm config set msvs_version 2019

    - name: Checkout the latest code
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v2-beta
      with:
        node-version: 16

    - name: install dependencies
      run: yarn install

    - name: build dependencies
      run: yarn build

    - name: cache node module
      id: cache-node
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-modules-${{ hashFiles('package.json') }}

  test:
    name: test
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    needs: setup
    steps:
    - name: Checkout the latest code
      uses: actions/checkout@v2

    - name: restore node module
      id: restore-node
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-modules-${{ hashFiles('package.json') }}

    - name: Run languages' packages' tests
      uses: GabrielBB/xvfb-action@v1
      if: ${{ !contains(matrix.os, 'windows') }}
      with:
        run: node -e "require('./script/run-package-tests')(/language|complete/)"
